export enum routers {
  MAIN = "/",
  ATTRACTIONS = "bukhara/sights.htm",
  CONTACTS = "contact",
  BUKHARA = "/bukhara.htm",
  TOURS = "/bukhara/tours.htm",
  ATTRACTION_DETAILS = "/sights/:ident.htm",
  HOTELS = "/hotels.htm",
  HOTEL_DETAILS = "/:ident.htm",
  AIRPORT = "/bukhara/airports.htm",
  HISTORY = "/bukhara/history.htm",
  MUSEUMS = "/bukhara/museums.htm",
  RELIGION = "/bukhara/religion.htm",
  
  MAIN_RUS = "/rus",
  ATTRACTIONS_RUS = "/rus/bukhara/sights.htm",
  CONTACTS_RUS = "/rus/contact",
  BUKHARA_RUS = "/rus/bukhara.htm",
  TOURS_RUS = "/rus/bukhara/tours.htm",
  ATTRACTION_DETAILS_RUS = "/rus/sights/:ident.htm",
  HOTELS_RUS = "/rus/hotels.htm",
  HOTEL_DETAILS_RUS = "/rus/:ident.htm",
  AIRPORT_RUS = "/rus/bukhara/airports.htm",
  HISTORY_RUS = "/rus/bukhara/history.htm",
  MUSEUMS_RUS = "/rus/bukhara/museums.htm",
  RELIGION_RUS = "/rus/bukhara/religion.htm"
}